CREATE DATABASE SPOTIFY;
 USE SPOTIFY;
CREATE TABLE MUSICAS(
id INT PRIMARY KEY,
nome VARCHAR(50),
duracao INT
);

CREATE TABLE ALBUM(
id_album INT PRIMARY KEY,
nome VARCHAR(50)
);

CREATE TABLE ARTISTA(
id INT PRIMARY KEY,
nome VARCHAR (50));

ALTER TABLE MUSICAS ADD FOREIGN KEY (id_album)
references ALBUM (id_album)